# Generated by Django 5.0.6 on 2024-06-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('division', models.CharField(max_length=20)),
                ('roll_num', models.IntegerField()),
                ('email', models.CharField(max_length=400)),
                ('uid', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
