# Generated by Django 5.0.6 on 2024-06-25 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=400)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='apis.division')),
            ],
        ),
    ]
