# Generated by Django 5.0.6 on 2024-06-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekschedule',
            name='daySchedule',
        ),
        migrations.AddField(
            model_name='weekschedule',
            name='daySchedule',
            field=models.ManyToManyField(related_name='daysSchedule', to='apis.dayschedule'),
        ),
    ]
