# Generated by Django 5.0.6 on 2024-06-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_announcements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='division',
        ),
        migrations.AddField(
            model_name='announcements',
            name='division',
            field=models.ManyToManyField(related_name='announcements', to='apis.division'),
        ),
    ]
