# Generated by Django 5.0.6 on 2024-06-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_year_weekschedule_week_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=400)),
                ('weeks', models.ManyToManyField(related_name='weekschedule', to='apis.weekschedule')),
            ],
        ),
    ]
