# Generated by Django 5.0.6 on 2024-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='none', max_length=400),
        ),
    ]
